## NumPy

NumPy (short for Numerical Python) is a Python library used for numerical and scientific computing. It provides powerful tools for working with large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these data structures efficiently. NumPy is widely used in data analysis, machine learning, and scientific computing due to its speed and flexibility.

### Key Features of NumPy

   **1. N-Dimensional Arrays:** NumPy arrays (ndarray) are faster and more efficient than Python lists for numerical operations.<br>
   **2. Mathematical Functions:** Includes functions for algebra, statistics, and complex numerical computations.<br>
   **3. Broadcasting:** Supports operations between arrays of different shapes.<br>
   **4. Integration with Other Libraries:** Often used with libraries like Pandas, Matplotlib, and Scikit-learn.<br>
   **5. Speed:** Operates at speeds closer to low-level languages like C, as it is implemented in C.

### How to create Numpy Arrays?
NumPy arrays can be created in multiple ways depending on the data or structure you need. Below are all the possible ways to create a NumPy array:<br>
We can use Numpy library to create arrays

In [1]:
import numpy as np

### 1. From a Python List or Tuple

Convert an existing list or tuple into a NumPy array using `np.array`.

In [2]:
import numpy as np

# From a list
arr_from_list = np.array([1, 2, 3, 4])
print("From list:", arr_from_list)

# From a tuple
arr_from_tuple = np.array((5, 6, 7, 8))
print("From tuple:", arr_from_tuple)

From list: [1 2 3 4]
From tuple: [5 6 7 8]


### 2. Using Built-in Functions

NumPy provides functions to create arrays with specific patterns

* a. `np.zeros`: Array of all zeros

In [23]:
zeros_array = np.zeros((3, 4))
print("Zeros Array:\n", zeros_array)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


* b. `np.ones`: Array of all ones

In [6]:
ones_array = np.ones((3, 2))
print("Ones Array:\n", ones_array)

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


* c. `np.empty`: Array with uninitialized values

In [7]:
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

Empty Array:
 [[2.12199579e-314 6.47208716e-312]
 [5.03946959e-321 6.95187041e-310]]


* d. `np.full`: Array filled with a specific value

In [8]:
full_array = np.full((2, 3), 7)
print("Full Array:\n", full_array)

Full Array:
 [[7 7 7]
 [7 7 7]]


### 3. Using Sequences

Create arrays with sequences of numbers.

* a. `np.arange`: Similar to Python's range

In [9]:
arr_range = np.arange(0, 10, 2)  # Start, stop, step
print("Arange Array:", arr_range)

Arange Array: [0 2 4 6 8]


* b. `np.linspace`: Specify the number of evenly spaced points

In [10]:
arr_linspace = np.linspace(0, 1, 5)  # Start, stop, num_points
print("Linspace Array:", arr_linspace)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


### 4. Identity and Diagonal Matrices

Create arrays representing identity or diagonal matrices.

* a. `np.eye`: Identity matrix

In [11]:
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


* b. `np.diag`: Diagonal matrix from a list

In [12]:
diag_matrix = np.diag([1, 2, 3])
print("Diagonal Matrix:\n", diag_matrix)

Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


### 5. Random Arrays

Generate arrays with random values.

#### a. Random values between 0 and 1

In [13]:
random_array = np.random.random((2, 2))
print("Random Array:\n", random_array)

Random Array:
 [[0.10337865 0.02511361]
 [0.15460146 0.97927016]]


####  b. Random integers

In [65]:
randint_array = np.random.randint(0, 10, (3, 4))  # Low, high, shape
print("Random Integers Array:\n", randint_array)

Random Integers Array:
 [[7 4 1 2]
 [0 3 0 5]
 [0 7 8 1]]


#### c. Normal distribution

In [15]:
normal_array = np.random.normal(0, 1, (2, 3))  # Mean, std, shape
print("Normal Distribution Array:\n", normal_array)

Normal Distribution Array:
 [[-0.72045135 -0.35334686 -1.21651265]
 [ 1.3147829  -1.37930883 -1.76732016]]


### 6. From Existing Data
* a. `np.copy`: Create a copy of an existing array

In [16]:
original_array = np.array([1, 2, 3])
copied_array = np.copy(original_array)
print("Copied Array:", copied_array)

Copied Array: [1 2 3]


* b. From another array’s shape

In [17]:
shape_array = np.ones_like(original_array)
print("Array with Same Shape as Original:\n", shape_array)

Array with Same Shape as Original:
 [1 1 1]


### 7. Reshaped Arrays

Create arrays with `reshaped` dimensions.

In [18]:
reshaped_array = np.arange(12).reshape(3, 4)
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 8. Using Custom Data Types

Specify a data type for the array.

In [20]:
dtype_array = np.array([1, 2, 3], dtype=float)
print("Array with Float Data Type:", dtype_array)

Array with Float Data Type: [1. 2. 3.]


## how to check dimension,shape and type of arrays?

### 1. Check Dimension (ndim)

The `ndim` attribute tells you the number of dimensions (axes) of the array.

In [24]:
import numpy as np

# Example array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Number of dimensions:", arr.ndim)  # Output: 2

Array:
 [[1 2 3]
 [4 5 6]]
Number of dimensions: 2


### 2. Check Shape (shape)

The `shape` attribute returns a tuple representing the size of the array along each dimension.

In [25]:
print("Shape of the array:", arr.shape)  # Output: (2, 3)

Shape of the array: (2, 3)


### 3. Check Data Type of Array Elements (dtype)

The `dtype` attribute provides the data type of the array elements.

In [26]:
print("Data type of elements:", arr.dtype)  # Output: int64 (or platform-specific int type)

Data type of elements: int32


### 4. Check Type of Array Object (type)

The `type` function tells you the type of the array object itself (usually `numpy.ndarray`).

In [27]:
print("Type of array object:", type(arr))  # Output: <class 'numpy.ndarray'>

Type of array object: <class 'numpy.ndarray'>


### 5. Check Total Number of Elements (size)

The `size` attribute gives the total number of elements in the array.

In [28]:
print("Total number of elements:", arr.size)  # Output: 6

Total number of elements: 6


### How to create Multidimensional Array?

In [29]:
import numpy as np

# 1D Array
arr_1d = np.array([1, 2, 3, 4])
print("1D Array:", arr_1d)

1D Array: [1 2 3 4]


In [32]:
arr_1d = np.array([1, 2, 3, 4]).reshape(2,2)
print("1D Array:", arr_1d)

1D Array: [[1 2]
 [3 4]]


In [37]:
# 2D Array
arr_2d = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr_2d)

2D Array:
 [[1 2]
 [3 4]]


In [31]:
# 3D Array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr_3d)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**NumPy arrays support a wide range of operations for efficient numerical computation. Here's a categorized list of all common operations you can perform on arrays:**

### 1. Arithmetic Operations

These operations are element-wise.

In [38]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Basic arithmetic
print("Addition:", arr1 + arr2)          # [5 7 9]
print("Subtraction:", arr1 - arr2)       # [-3 -3 -3]
print("Multiplication:", arr1 * arr2)    # [4 10 18]
print("Division:", arr1 / arr2)          # [0.25 0.4 0.5]
print("Exponentiation:", arr1 ** 2)      # [1 4 9]

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponentiation: [1 4 9]


### 2. Aggregation Operations

These functions compute summary statistics.

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Basic aggregation
print("Sum:", arr.sum())                 # 21
print("Mean:", arr.mean())               # 3.5
print("Max:", arr.max())                 # 6
print("Min:", arr.min())                 # 1

# Along specific axes
print("Sum along rows:", arr.sum(axis=1))  # [6 15]
print("Sum along columns:", arr.sum(axis=0))  # [5 7 9]

Sum: 21
Mean: 3.5
Max: 6
Min: 1
Sum along rows: [ 6 15]
Sum along columns: [5 7 9]


### 3. Logical and Comparison Operations

Perform element-wise comparisons or logical tests.

In [40]:
arr = np.array([1, 2, 3, 4])

# Comparison
print("Greater than 2:", arr > 2)        # [False False  True  True]
print("Equal to 3:", arr == 3)           # [False False  True False]

# Logical operations
print("Any > 2:", (arr > 2).any())       # True
print("All > 0:", (arr > 0).all())       # True

Greater than 2: [False False  True  True]
Equal to 3: [False False  True False]
Any > 2: True
All > 0: True


### 4. Array Manipulation
#### a. Reshaping

Change the shape of the array without altering its data.

In [41]:
arr = np.arange(1, 13)
reshaped = arr.reshape(3, 4)
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### b. Flattening

Convert a multi-dimensional array into a 1D array.

In [42]:
print("Flattened Array:", reshaped.flatten())

Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


#### c. Transposing

Switch rows and columns for 2D arrays or swap axes for higher dimensions.

In [43]:
print("Transpose:\n", reshaped.T)

Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


#### d. Concatenation

Combine arrays along a specific axis.

In [44]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along rows
print("Concatenated Rows:\n", np.concatenate((arr1, arr2), axis=0))

# Concatenate along columns
print("Concatenated Columns:\n", np.concatenate((arr1, arr2), axis=1))

Concatenated Rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated Columns:
 [[1 2 5 6]
 [3 4 7 8]]


#### e. Splitting

Split an array into smaller sub-arrays.

In [45]:
arr = np.arange(1, 10)
splits = np.split(arr, 3)
print("Split Arrays:", splits)

Split Arrays: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


### 5. Indexing and Slicing

Access specific elements or slices of the array.

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Access specific element
print("Element [0,1]:", arr[0, 1])  # 2

# Slice rows and columns
print("First row:", arr[0, :])  # [1 2 3]
print("First column:", arr[:, 0])  # [1 4]

# Boolean indexing
print("Elements > 3:", arr[arr > 3])  # [4 5 6]

Element [0,1]: 2
First row: [1 2 3]
First column: [1 4]
Elements > 3: [4 5 6]


### 6. Mathematical Operations
#### a. Trigonometric Functions

In [47]:
angles = np.array([0, np.pi/2, np.pi])
print("Sine:", np.sin(angles))       # [0. 1. 0.]
print("Cosine:", np.cos(angles))     # [ 1. 0. -1.]

Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


#### b. Exponent and Logarithm

In [48]:
arr = np.array([1, 2, 3])
print("Exponential:", np.exp(arr))   # [2.71828183 7.3890561  20.08553692]
print("Logarithm:", np.log(arr))     # [0.         0.69314718 1.09861229]

Exponential: [ 2.71828183  7.3890561  20.08553692]
Logarithm: [0.         0.69314718 1.09861229]


### 7. Sorting

In [49]:
arr = np.array([[3, 1, 2], [6, 5, 4]])

# Sort each row
print("Sorted Rows:\n", np.sort(arr, axis=1))

# Sort entire array as flattened
print("Sorted Flattened:", np.sort(arr, axis=None))

Sorted Rows:
 [[1 2 3]
 [4 5 6]]
Sorted Flattened: [1 2 3 4 5 6]


### 8. Copying and Cloning

In [50]:
arr = np.array([1, 2, 3])
arr_copy = arr.copy()
print("Copied Array:", arr_copy)

Copied Array: [1 2 3]


### 9. Linear Algebra Operations

Use `numpy.linalg` for advanced matrix operations.

In [51]:
from numpy.linalg import inv, det

matrix = np.array([[1, 2], [3, 4]])

# Matrix inverse
print("Inverse:\n", inv(matrix))

# Determinant
print("Determinant:", det(matrix))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004


### 10. Statistical Operations

In [52]:
arr = np.array([1, 2, 3, 4, 5])

print("Mean:", np.mean(arr))         # 3.0
print("Median:", np.median(arr))     # 3.0
print("Standard Deviation:", np.std(arr))  # 1.414

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


### 11. Random Number Operations

In [53]:
random_array = np.random.randint(1, 10, (2, 3))  # 2x3 random integers
print("Random Array:\n", random_array)

Random Array:
 [[4 6 8]
 [5 5 9]]


### 13. Advanced Indexing Operations
#### a. Fancy Indexing

Index arrays using other arrays or lists.

In [54]:
arr = np.array([10, 20, 30, 40, 50])

# Select elements using indices
indices = [0, 3, 4]
print("Fancy Indexed Array:", arr[indices])  # [10 40 50]

Fancy Indexed Array: [10 40 50]


#### b. Index Arrays with Boolean Masks

In [55]:
arr = np.array([1, 2, 3, 4, 5])

mask = arr % 2 == 0  # Find even numbers
print("Even Numbers:", arr[mask])  # [2 4]

Even Numbers: [2 4]


### 14. Statistical and Probability Distributions

Use `np.random` for sampling from distributions.
#### a. Uniform Distribution

In [56]:
uniform = np.random.uniform(0, 1, (3, 3))
print("Uniform Distribution:\n", uniform)

Uniform Distribution:
 [[0.37756668 0.40363578 0.74188257]
 [0.28366982 0.93972115 0.55268099]
 [0.45012324 0.72390242 0.33882264]]


#### b. Normal Distribution

In [57]:
normal = np.random.normal(0, 1, (2, 3))
print("Normal Distribution:\n", normal)

Normal Distribution:
 [[ 1.48059705 -0.06854561  1.04631125]
 [-1.52049987 -1.09034194  1.30758795]]


#### c. Binomial Distribution

In [58]:
binomial = np.random.binomial(10, 0.5, 5)  # 10 trials, p=0.5
print("Binomial Distribution:", binomial)

Binomial Distribution: [3 5 7 6 5]


### 15. Complex Number Support

NumPy arrays can handle complex numbers.

In [59]:
arr = np.array([1 + 2j, 3 + 4j])

# Operations with complex numbers
print("Real Part:", arr.real)  # [1. 3.]
print("Imaginary Part:", arr.imag)  # [2. 4.]
print("Conjugate:", np.conj(arr))  # [1.-2.j 3.-4.j]

Real Part: [1. 3.]
Imaginary Part: [2. 4.]
Conjugate: [1.-2.j 3.-4.j]


### 16. Cumulative Operations
#### a. Cumulative Sum

In [60]:
arr = np.array([1, 2, 3, 4])
print("Cumulative Sum:", np.cumsum(arr))  # [1 3 6 10]

Cumulative Sum: [ 1  3  6 10]


#### b. Cumulative Product

In [61]:
print("Cumulative Product:", np.cumprod(arr))  # [1 2 6 24]

Cumulative Product: [ 1  2  6 24]


### 17. Element-Wise Operations with Custom Functions

Use `np.vectorize` to apply custom functions element-wise

In [62]:
def square(x):
    return x ** 2

arr = np.array([1, 2, 3])
vectorized_square = np.vectorize(square)
print("Squared Array:", vectorized_square(arr))  # [1 4 9]

Squared Array: [1 4 9]


### 18. Matrix Multiplication and Dot Products
#### a. Matrix Multiplication (@ or np.matmul)

In [63]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:\n", A @ B)

Matrix Multiplication:
 [[19 22]
 [43 50]]


#### b. Dot Product

In [64]:
dot_product = np.dot(arr1, arr2)
print("Dot Product:", dot_product)

Dot Product: [[19 22]
 [43 50]]


### 19. Stacking

#### horizontal stacking
horizaontal stacking means placing arrays side by side 

In [69]:
a4 = np.arange(12).reshape(3,4)
print(a4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [70]:
a5 = np.arange(12,24).reshape(3,4)
print(a5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [71]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

#### Vertical Stacking
vertical stacking means placing arrays one upon other vertically

In [72]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [73]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [74]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


#### Broadcasting Rules

**1. Make the two arrays have the same number of dimensions.**<br>
- If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.<br>

**2. Make each dimension of the two arrays the same size.**<br>
- If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
- If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">

In [75]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [76]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [77]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [78]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [79]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [80]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [81]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

### Difference between Numpy array and Python List

| **Feature**               | **NumPy Array**                                      | **Python List**                                   |
|---------------------------|-----------------------------------------------------|-------------------------------------------------|
| **Data Type**             | Homogeneous: All elements must have the same type.  | Heterogeneous: Can contain different data types. |
| **Performance**           | Faster: Optimized for numerical computations using C. | Slower: Operations involve Python's interpreter overhead. |
| **Memory Usage**          | More efficient: Fixed data type reduces memory usage. | Less efficient: Stores pointers for each element. |
| **Element-wise Operations** | Supported directly (e.g., `arr + 1`, `arr * 2`).    | Not supported; requires loops or comprehension. |
| **Functionality**         | Provides mathematical, statistical, and logical functions. | Limited to built-in Python operations and libraries. |
| **Dimensionality**        | Supports multi-dimensional arrays (e.g., 2D, 3D).   | Only 1D, but lists of lists can mimic multi-dimensional arrays. |
| **Indexing and Slicing**  | Advanced slicing and broadcasting supported.         | Basic slicing; less flexible.                   |
| **Type Enforcement**      | Enforces single data type for all elements.          | Allows mixing types (e.g., `int`, `str`).       |
| **Flexibility**           | Less flexible: Fixed size, no direct appending/inserting. | Flexible: Can dynamically grow or shrink.       |
| **Library Integration**   | Ideal for numerical computations (e.g., SciPy, TensorFlow). | General-purpose but slower for numerical tasks. |
| **Use Case**              | Best for numerical data, linear algebra, and machine learning. | General-purpose data storage and manipulation.  |


### Why do we need Numpy Array?

We need NumPy arrays because they provide several advantages over traditional Python lists for numerical computations, data analysis, and scientific programming. Here’s a detailed explanation

#### 1. Performance (Speed)

   * NumPy arrays are implemented in C, enabling vectorized operations that are much faster than looping through Python lists.
   * They eliminate the overhead of Python’s dynamic typing, making operations significantly faster.

In [84]:
import numpy as np
import time

# NumPy array
arr = np.arange(1_000_000)
start = time.time()
arr = arr * 2
print("NumPy Time:", time.time() - start)

# Python list
lst = list(range(1_000_000))
start = time.time()
lst = [x * 2 for x in lst]
print("List Time:", time.time() - start)

NumPy Time: 0.003993511199951172
List Time: 0.18100476264953613


**Result:** NumPy is typically `10x to 100x` faster than Python lists

### 2. Memory Efficiency

   * NumPy arrays store elements in contiguous memory blocks, ensuring efficient storage and retrieval.
   * Python lists store references (pointers) to objects, which adds overhead.

In [85]:
import numpy as np
import sys

# Memory usage of a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("NumPy Array Memory (bytes):", arr.nbytes)

# Memory usage of a Python list
lst = [1, 2, 3, 4, 5]
print("Python List Memory (bytes):", sys.getsizeof(lst) + sum(sys.getsizeof(i) for i in lst))

NumPy Array Memory (bytes): 20
Python List Memory (bytes): 244


**Result:** NumPy arrays use significantly less memory.

#### 3. Vectorized Operations

    Operations in NumPy are applied element-wise without the need for explicit loops, making code more concise and efficient.

In [86]:
# NumPy array operation
arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)  # [11 12 13 14 15]

# Python list operation
lst = [1, 2, 3, 4, 5]
print([x + 10 for x in lst])  # [11, 12, 13, 14, 15]

[11 12 13 14 15]
[11, 12, 13, 14, 15]
